---
engines:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
      Identical code:
        enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    checks:
      complexity:
        enabled: false
    exclude_fingerprints:
      - b48b8d51245ef95a52fc9bfe0132301d
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- test/
- lib/utils.js
- Gruntfile.js
