/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "field_daikinIp": {                              "en": "IP of Daikin Device",                             "de": "IP des Daikin-Geräts",                            "ru": "IP устройства Daikin",                            "pt": "IP do dispositivo Daikin",                        "nl": "IP van Daikin Device",                            "fr": "IP du périphérique Daikin",                       "it": "IP del dispositivo Daikin",                       "es": "IP del dispositivo Daikin",                       "pl": "Adres IP urządzenia Daikin",                      "zh-cn": "大金设备的IP"},
    "field_pollingInterval": {                       "en": "Data update interval",                            "de": "Datenaktualisierungsintervall",                   "ru": "Интервал обновления данных",                      "pt": "Intervalo de atualização de dados",               "nl": "Gegevensupdate-interval",                         "fr": "Intervalle de mise à jour des données",           "it": "Intervallo di aggiornamento dei dati",            "es": "Intervalo de actualización de datos",             "pl": "Częstotliwość aktualizacji danych",               "zh-cn": "数据更新间隔"},
    "field_useGetToPost": {                          "en": "Send commands using HTTP GET",                    "de": "Senden Sie Befehle mit HTTP GET",                 "ru": "Отправить команды с помощью HTTP GET",            "pt": "Enviar comandos usando HTTP GET",                 "nl": "Verzend opdrachten met HTTP GET",                 "fr": "Envoyer des commandes à l'aide de HTTP GET",      "it": "Invia comandi utilizzando HTTP GET",              "es": "Enviar comandos usando HTTP GET",                 "pl": "Wysyłaj polecenia za pomocą protokołu HTTP GET",  "zh-cn": "使用HTTP GET发送命令"},
    "heading_GeneralSettings": {                     "en": "General settings",                                "de": "Generelle Einstellungen",                         "ru": "общие настройки",                                 "pt": "Configurações Gerais",                            "nl": "Algemene instellingen",                           "fr": "réglages généraux",                               "it": "impostazioni generali",                           "es": "Configuración general",                           "pl": "Ustawienia główne",                               "zh-cn": "常规设置"},
    "info_daikinIp": {                               "en": " ",                                               "de": " ",                                               "ru": " ",                                               "pt": " ",                                               "nl": " ",                                               "fr": " ",                                               "it": " ",                                               "es": " ",                                               "pl": " ",                                               "zh-cn": " "},
    "info_pollingInterval": {                        "en": " ",                                               "de": " ",                                               "ru": " ",                                               "pt": " ",                                               "nl": " ",                                               "fr": " ",                                               "it": " ",                                               "es": " ",                                               "pl": " ",                                               "zh-cn": " "},
    "info_useGetToPost": {                           "en": "(only needed for 1.x WLAN-Firmwares if it else doesn't work)", "de": "(wird nur für 1.x WLAN-Firmwares benötigt, wenn es sonst nicht funktioniert)", "ru": "(требуется только для 1.x WLAN-прошивок, если они не работают)", "pt": "(necessário apenas para os firmware WLAN 1.x, caso contrário não funcione)", "nl": "(alleen nodig voor 1.x WLAN-Firmwares als het anders niet werkt)", "fr": "(nécessaire uniquement pour les micrologiciels WLAN 1.x si cela ne fonctionne pas)", "it": "(necessario solo per firmware WLAN 1.x se non funziona diversamente)", "es": "(solo es necesario para 1.x WLAN-Firmwares si no funciona)", "pl": "(potrzebne tylko dla oprogramowania układowego 1.x WLAN, jeśli w innym przypadku nie działa)", "zh-cn": "（如果其他1.x WLAN固件不起作用，则仅需要使用该固件）"},
    "page_title": {                                  "en": "Daikin Adapter Settings",                         "de": "Daikin Adapter Einstellungen",                    "ru": "Настройки адаптера Daikin",                       "pt": "Definições do adaptador Daikin",                  "nl": "Daikin Adapterinstellingen",                      "fr": "Paramètres de l'adaptateur Daikin",               "it": "Impostazioni dell'adattatore Daikin",             "es": "Configuración del adaptador Daikin",              "pl": "Ustawienia adaptera Daikin",                      "zh-cn": "大金适配器设置"},
};